echo "****************************************************************************************************************"
echo "                                                                                                                "
echo "                                               Apache php 8.1                                                   "
echo "                                                                                                                "
echo "             Install nodejs: install-nodejs VERSION, install-nodejs 18                                          "
echo "                                                                                                                "
echo "             MC: Midnight Commander                                                                             "
echo "                                                                                                                "
echo "             Enable/Disable xdebug: xdebug on|off                                                               "
echo "                                                                                                                "
echo "             Enable/Disable xhprof: xhprof on|off                                                               "
echo "                                                                                                                "
echo "             Server name: $SERVERNAME                                                                           "
echo "                                                                                                                "
echo "             Server alias: $SERVERALIAS                                                                         "
echo "                                                                                                                "
echo "             Server alias: /var/www/html/$DOCUMENTROOT                                                          "
echo "                                                                                                                "
echo "                                                                                                                "
echo "****************************************************************************************************************"
su - web